### ISSUE TITLE
US1 List of projects

### ISSUE THREAD

**Issue by VolkerJacobsen** [VolkerJacobsen/capstone-volker#1]
## Value proposition

As an user
I want a list of all projects
In order to get an overview of all available projects

## Description

![Image](https://user-images.githubusercontent.com/130739212/250923376-faa9866d-e809-49fd-9ed5-c8b3db777484.png)

## Acceptance criteria

- [ ] All projects are displayed as a list
- [ ] Each projects image is displayed
- [ ] Each projects title is displayed
- [ ] Each projects short description is displayed

## Tasks

- [ ] Create a data.js with all project details
- [ ] Create the component projects to render a list
- [ ] Create the component ProjectPreview
- [ ] ProjectPreview props: title, image, short-description

**Comment by djfarly** [comment]
Hej just a tiny note: `short-description` should probably be `shortDescription`.

otherwise you're good to go!
