### ISSUE TITLE
US5 Add a "Add project button"

### ISSUE THREAD

**Issue by VolkerJacobsen** [VolkerJacobsen/capstone-volker#10]
## Value proposition

As a user
I expect a certain level of structure
In order to not get overwhelmed by too much information right from the beginning.

## Description

![Image](https://user-images.githubusercontent.com/130739212/253498855-0a70de5f-547b-4f3a-802f-e06ff2075743.jpg)

## Acceptance criteria

- [ ] A "Add your project" button is displayed in the Homepage
- [ ] The form is displayed after clicking the button

## Tasks

- [ ] Create a "Add your project"-button component
- [ ] Link the form to the "Add your project" button
