### ISSUE TITLE
US4 - Filter projects by category

### ISSUE THREAD

**Issue by VolkerJacobsen** [VolkerJacobsen/capstone-volker#11]
## Value proposition

As a user
I would like to filter the projects by category
In order to see only the projects I am interested in

## Description

![Image](https://user-images.githubusercontent.com/130739212/253502146-78007a23-6fbe-401f-80e6-2a9e83546b0b.jpg)

## Acceptance criteria

- [ ] A Select-Button is created in the header
- [ ] Categories are "Politics", "Environment", "Community"
- [ ] After clicking a specific category I only see those projects of the specific category

## Tasks

- [ ] Create a "Select Button" with the options of all categories
- [ ] Create a "All projects" button to get back to see all projects
