### ISSUE TITLE
US6 About us/ navigation

### ISSUE THREAD

**Issue by VolkerJacobsen** [VolkerJacobsen/capstone-volker#12]
## Value proposition

As a user
I want to know more about getInvolved 
In order to be able to relate better with the organization

## Description

![Image](https://user-images.githubusercontent.com/130739212/253505112-78a40bad-028e-40dc-ad7f-6d0d0708668b.jpg)

## Acceptance criteria

- [ ] A "About us" page is created with detailed information about getInvolved
- [ ] A navigation is created which leads to "all projects" and "about us"
- [ ] A "all projects button is created in the Header

## Tasks

- [ ] Create a navigation leading to "all projects" and "about us"
- [ ] Create a "About us" -page in the index.js
