### ISSUE TITLE
US7 Bookmark projects

### ISSUE THREAD

**Issue by VolkerJacobsen** [VolkerJacobsen/capstone-volker#13]
## Value proposition

As a user
I would like to bookmark projects
In order to set my own favorites

## Description

![Image](https://github.com/VolkerJacobsen/capstone-volker/assets/130739212/be3bf064-2c26-47be-84de-e0199deacc18)

## Acceptance criteria

- [ ] A bookmark icon is displayed in each project
- [ ] A toggle function is set 
- [ ] bookmarked projects are displayed in a favorites page
- [ ] A "favorite" page is displayed in the navigation

## Tasks

- [ ] Set bookmark icons on each project
- [ ] Set a toggle function 
- [ ] Create a favorite page
- [ ] Link the favorite page to the navigation

**Comment by DErdmann1** [comment]
Perfect :)
