### ISSUE TITLE
US8 add Comment section

### ISSUE THREAD

**Issue by VolkerJacobsen** [VolkerJacobsen/capstone-volker#17]
## Value proposition

As a user
I would like to comment on specific projects
In order to get more detailed information that could also be useful for other users

## Description

![Image](https://github.com/VolkerJacobsen/capstone-volker/assets/130739212/46d53c72-22c9-4b72-b6fd-b5aa459eb631)

## Value proposition

As a user
I would like to leave questions and remarks for the organizers.
In order to get further information that might also be helpful for other users

## Description

![Image](https://github.com/VolkerJacobsen/capstone-volker/assets/130739212/59f1890b-eaa4-45db-88f7-26980291a902)

## Acceptance criteria

- [ ] A comment section is created in the ProjectDetail page
- [ ] Comments can be submitted and display in the comment section
- [ ] Comments can be edited and deleted

## Tasks

- [ ] Add a comment section in the ProjectDetail.js
- [ ] Add a Comment Input field
- [ ] Add a edit and delete Button to the comments submitted

**Comment by ekat-br** [comment]
Hi @VolkerJacobsen, nice user story! 

Just a minor suggestion: 
One Acceptance Criteria is: "Comments can be edited and deleted". At this point I would expect it to be described in more detail in the tasks. For example, build the function to edit and delete entries. I would also expect an edit button in the description image at this point, as your delete button is also included in the image. 

Keep up the good work!🚀

**Comment by SelcoD** [comment]
LGTM !
