### ISSUE TITLE
US9 Add image upload to Cloudinary

### ISSUE THREAD

**Issue by VolkerJacobsen** [VolkerJacobsen/capstone-volker#18]
## Value proposition

As a project publisher
I would like to upload images to my project
In order to get get more engagement for my project

## Description

![Image](https://github.com/VolkerJacobsen/capstone-volker/assets/130739212/ba696d6c-28ad-43dc-ba0d-167294e14b43)

## Acceptance criteria

- [ ] Add a image file upload to the projects form
- [ ] Image can be uploaded through the form
- [ ] Image is uploaded to Cloudinary
- [ ] Image is downstreamed from Cloudinary and displayed in the ProjectPreview

## Tasks

- [ ] Add image file upload to ProjectForm
- [ ] Create function to upload image to Cloudinary
- [ ] Upload all existing images to Cloudinary
- [ ] Edit the imageSource in ProjectPreview and ProjectDetail

**Comment by HannesOster** [comment]
Hey Volker,

looks good!

**Comment by VolkerJacobsen** [comment]
Thanks! ;)
