### ISSUE TITLE
US2 Project form

### ISSUE THREAD

**Issue by VolkerJacobsen** [VolkerJacobsen/capstone-volker#2]
## Value proposition

As a user
I want to add my project
In order to find other users to involve with my project

## Description

![Image](https://user-images.githubusercontent.com/130739212/251413825-f89b9164-86cd-416c-be96-b048d7131142.jpg)

## Acceptance criteria

- [ ] A form is created and displayed
- [ ] The form contains input fields for organizers name, category to select, title, short- and long description and an email address
- [ ] All form fields are labeled properly
- [ ] All form fields are set as mandatory/ required. If those fields are not populated the user is prompted to do so.
- [ ] The short description has a max. character limit of 50, the long description of 300 and the title of 40 characters.
- [ ] A submit button is created to submit the form
- [ ] After submitting the form the project is saved and displayed in the "all-projects" page
- [ ] A success message is displayed.

## Tasks

- [ ] Create a form component
- [ ] after form submit the project is rendered in the "all projects" page

**Comment by JessicaLoers** [comment]
**Hi @VolkerJacobsen ✌️** well done. 

Especially for user stories that contain a form, there are numerous **acceptance criteria** that we as developers didn't even think about in the first step. 

**Validation:** What happens if users submit the form with incorrect or no data?

**Redirection:** Where do users end up after submitting the form? Are they redirected to the page where the new project is listed?

**Confirmation:** Is there a hint or confirmation that users have successfully added their project, for example in the form of a toast message?

Here are some examples of how you might describe the Acceptance Criteria in more detail, additional to your listed ones.

- All form fields should have clear labels, and fields that require specific formats should have placeholders to guide the user on the expected input format.
- The form should have validation rules to check that all mandatory fields are filled before submission. If not, the form should prompt the user to fill in the missing details.
- The "Project Title", "Project Organizer",  and "Short Description"fields should have character limits to ensure concise and clear information.
- When the user has filled in all the required fields and submitted the form, the project is saved, a success message is displayed and the user is redirected to the project overview page.
- The newly added project should be visible on the dashboard or overview page(?) 

Maybe these examples will help you to get used to the topic ☺️

**Comment by CorneliusMoe** [comment]
> **Redirection:** Where do users end up after submitting the form? Are they redirected to the page where the new project is listed?
> 

Looks very good to me, the only part missing is the Redirection, like Jessica said: Where is the User redirected to, after submitting the form? 

A big part of my app is also a Form so maybe we could work together on this in the coming days.

**Comment by VolkerJacobsen** [comment]
Hi Cornelius, thanks for your feedback. Since the form is included in the "all projects" page first, he or she will not be redirected but stay on the same page. At a later stage I will move the form to a seperate page and then the user will be forwarded. 
Yes, let´s work together. Would be helpful and fun.

**Comment by CorneliusMoe** [comment]
Alright, thanks for the explanation and I'm looking forward to working together. Green Checkmark coming up
