### ISSUE TITLE
US10 Final Styling

### ISSUE THREAD

**Issue by VolkerJacobsen** [VolkerJacobsen/capstone-volker#21]
## Value proposition

As a user
I expect the app to be responsive
In order to have a perfect user experience

## Acceptance criteria

- [ ] All pages and components are rendered in a decent responsive design

## Tasks

- [ ] Add responsiveness to all pages and components
- [ ] Clean up code and create specific CSS-files
