### ISSUE TITLE
US11 Implementation of MongoDB

### ISSUE THREAD

**Issue by VolkerJacobsen** [VolkerJacobsen/capstone-volker#22]
## Value proposition

As a user and a project organizer
I want my interactions on the app to be persistent
In order to make real use of the app

## Acceptance criteria

- [ ] All project data is moved to MongoDB
- [ ] All new projects are saved in MongoDB 
- [ ] Source-Links of uploaded images in Cloudinary are saved in MongoDB
- [ ] Comments are saved in MongoDB

## Tasks

- [ ] Move all data to MongoDB
- [ ] All new projects are saved in MongoDB
- [ ] Source-Links uploaded to Cloudinary are saved correctly in MongoDB
- [ ] Data in the Comment-Section is stored in MongoDB
