### ISSUE TITLE
US3 Project detail page

### ISSUE THREAD

**Issue by VolkerJacobsen** [VolkerJacobsen/capstone-volker#3]
## Value proposition

As a user
I want to see more detailed information of all projects
In order to get all necessary information to make a decision about my potential involvement.

## Description

![Image](https://github.com/VolkerJacobsen/capstone-volker/assets/130739212/3de08d4b-31e1-46b4-95ef-d1617a38ded5)

## Acceptance criteria

- [ ] Create a ProjectDetail page
- [ ] The ProjectDetail component renders the title, organizer, a longer description an image and the contact email-address
- [ ] The ProjectDetail page is accessed by clicking the project in the "all projects" page
- [ ] A "all projects" button is created in the header of the App that allows users to go back to the "all-projects" page

## Tasks

- [ ] Create a detail page for all projects
- [ ] make the detail page accessible by clicking the individual projects in the "all-projects" page

**Comment by JessicaLoers** [comment]
**It' me again @VolkerJacobsen 😁**

**Value Proposition:**
_A nitpicky comment to further describe the benefit of this feature to the user._
[...]
**In order to** get all necessary information _to make a decision about my potential involvement._

**Acceptance Criteria:**
-Please add to your acceptance criteria, how the user can go back from the details page to the all projects page. 

**Description / Wire Frame:**
- another nitpicky note: would be nicer to use real content instead of the lorem ipsum text.

**Comment by DErdmann1** [comment]
LGTM now! :) Super detailed!
